Repository greshake/i3status-rust, pull requests merged in 2020-10, with the labels that each got.

#822 Signal support
  Cargo.lock
  Cargo.toml
  blocks.md
  src/blocks.rs
  src/blocks/custom.rs
  src/main.rs
  src/signals.rs
Labels: enhancement

#851 Add new Notify block
  src/blocks.rs
  src/blocks/notify.rs
  src/icons.rs
Labels: enhancement

#858 bluetooth block: add option to hide block when device is disconnected
  src/blocks/bluetooth.rs
Labels: enhancement

#860 custom block: add option to hide block when output is empty
  blocks.md
  src/blocks/custom.rs
Labels: enhancement

#863 time block: support locales
  Cargo.lock
  Cargo.toml
  blocks.md
  src/blocks/time.rs
  src/de.rs
Labels: enhancement

#864 prepare for new release by bumping deps
  Cargo.lock
  Cargo.toml
Labels: rustc/dependency versions

#872 graph widget: remove underscore
  src/widgets/graph.rs
Labels: fonts-and-rendering

#866 Fix spacing for inline widgets
  src/blocks/net.rs
  src/blocks/nvidia_gpu.rs
  src/blocks/temperature.rs
  src/widget.rs
  src/widgets/button.rs
  src/widgets/graph.rs
  src/widgets/rotatingtext.rs
  src/widgets/text.rs
Labels: changes requested, enhancement, fonts-and-rendering

#877 memory block: remove old debug code
  src/blocks/memory.rs
Labels: cleanup

#885 Revert #869
  src/blocks/net.rs
Labels: bug

#888 music block: add option to ignore certain players
  blocks.md
  src/blocks/music.rs
Labels: enhancement

#892 music block: add `hide_when_empty` option
  blocks.md
  src/blocks/music.rs
Labels: enhancement

#882 backlight: support nonlinear brightness
  blocks.md
  src/blocks/backlight.rs
Labels: enhancement

#895 temperature: Add Fahrenheit support.
  blocks.md
  src/blocks/temperature.rs
Labels: enhancement

#899 custom block: make `command` and `cycle` actually mutually exclusive
  src/blocks/custom.rs
Labels: configuration

#902 ibus block: improve IBus detection
  src/blocks/ibus.rs
Labels: enhancement
