Repository greshake/i3status-rust, pull requests merged in 2020-11, with the labels that each got.

#906 music block: overhaul update mechanism
  src/blocks/music.rs
Labels: enhancement

#908 diskspace block: fix panic when no icon defined
  src/blocks/disk_space.rs
Labels: bug

#909 tree-wide: fix all Clippy warnings
  src/blocks/ibus.rs
  src/blocks/music.rs
  src/blocks/net.rs
  src/blocks/notify.rs
  src/blocks/nvidia_gpu.rs
  src/signals.rs
Labels: cleanup

#910 kdeconnect block: fix panic when no icon exists
  src/blocks/kdeconnect.rs
Labels: bug

#911 xrandr block: remove hardcoded icons
  blocks.md
  src/blocks/xrandr.rs
  src/icons.rs
Labels: fonts-and-rendering

#912 battery block: clamp 'time remaining' values to something more realistic
  src/blocks/battery.rs
Labels: bug

#914 music block: limit mouse events when no players available
  src/blocks/music.rs
Labels: bug

#921 tree wide: use simple 16 byte random string for UUID
  Cargo.lock
  Cargo.toml
  src/blocks/backlight.rs
  src/blocks/battery.rs
  src/blocks/bluetooth.rs
  src/blocks/cpu.rs
  src/blocks/custom.rs
  src/blocks/custom_dbus.rs
  src/blocks/disk_space.rs
  src/blocks/docker.rs
  src/blocks/focused_window.rs
  src/blocks/github.rs
  src/blocks/hueshift.rs
  src/blocks/ibus.rs
  src/blocks/kdeconnect.rs
  src/blocks/keyboard_layout.rs
  src/blocks/load.rs
  src/blocks/maildir.rs
  src/blocks/memory.rs
  src/blocks/music.rs
  src/blocks/net.rs
  src/blocks/networkmanager.rs
  src/blocks/notify.rs
  src/blocks/notmuch.rs
  src/blocks/nvidia_gpu.rs
  src/blocks/pacman.rs
  src/blocks/pomodoro.rs
  src/blocks/sound.rs
  src/blocks/speedtest.rs
  src/blocks/taskwarrior.rs
  src/blocks/temperature.rs
  src/blocks/template.rs
  src/blocks/time.rs
  src/blocks/toggle.rs
  src/blocks/uptime.rs
  src/blocks/watson.rs
  src/blocks/weather.rs
  src/blocks/xrandr.rs
  src/util.rs
Labels: cleanup

#924 Fix alternating tint logic when blocks are hidden
  src/main.rs
  src/util.rs
Labels: fonts-and-rendering

#926 net block: do not error out when arrays are empty
  src/blocks/net.rs
Labels: bug

#927 Layout + tinting rework
  src/util.rs
Labels: fonts-and-rendering

#923 [blocks] fix equal spacing in battery & sound & networkmanager
  src/blocks/battery.rs
  src/blocks/networkmanager.rs
  src/blocks/sound.rs
  src/widgets/text.rs
Labels: fonts-and-rendering

#930 music block: allow right click to cycle between available players
  src/blocks/music.rs
Labels: enhancement

#933 music block: fix widget spacing
  src/blocks/music.rs
Labels: fonts-and-rendering

#932 Music block: Fix `hide_when_empty` not working
  src/blocks/music.rs
Labels: bug

#937 music block: use unique identifiers for widgets
  src/blocks/music.rs
Labels: bug

#939 keyboard_layout: add default fallback for sway driver
  blocks.md
  src/blocks/keyboard_layout.rs
Labels: bug

#940 keyboard_layout: add `variant` format specifier for localebus
  blocks.md
  src/blocks/keyboard_layout.rs
Labels: enhancement

#942 Fix clippy warnings
  src/blocks/backlight.rs
  src/blocks/battery.rs
  src/blocks/bluetooth.rs
  src/blocks/cpu.rs
  src/blocks/custom.rs
  src/blocks/custom_dbus.rs
  src/blocks/disk_space.rs
  src/blocks/docker.rs
  src/blocks/focused_window.rs
  src/blocks/github.rs
  src/blocks/hueshift.rs
  src/blocks/ibus.rs
  src/blocks/kdeconnect.rs
  src/blocks/keyboard_layout.rs
  src/blocks/load.rs
  src/blocks/maildir.rs
  src/blocks/memory.rs
  src/blocks/music.rs
  src/blocks/net.rs
  src/blocks/networkmanager.rs
  src/blocks/notify.rs
  src/blocks/nvidia_gpu.rs
  src/blocks/pacman.rs
  src/blocks/pomodoro.rs
  src/blocks/sound.rs
  src/blocks/speedtest.rs
  src/blocks/taskwarrior.rs
  src/blocks/temperature.rs
  src/blocks/template.rs
  src/blocks/time.rs
  src/blocks/toggle.rs
  src/blocks/uptime.rs
  src/blocks/watson.rs
  src/blocks/weather.rs
  src/blocks/xrandr.rs
  src/util.rs
Labels: cleanup

#938 Add native theme
  img/themes/native.png
  src/themes.rs
  src/util.rs
  src/widget.rs
  themes.md
Labels: themes/icons

#943 Add new Apt block
  src/blocks.rs
  src/blocks/apt.rs
Labels: enhancement

#944 tree-wide: reorder imports
  src/blocks/backlight.rs
  src/blocks/battery.rs
  src/blocks/bluetooth.rs
  src/blocks/cpu.rs
  src/blocks/disk_space.rs
  src/blocks/docker.rs
  src/blocks/ibus.rs
  src/blocks/keyboard_layout.rs
  src/blocks/maildir.rs
  src/blocks/memory.rs
  src/blocks/net.rs
  src/blocks/networkmanager.rs
  src/blocks/notmuch.rs
  src/blocks/nvidia_gpu.rs
  src/blocks/pacman.rs
  src/blocks/pomodoro.rs
  src/blocks/sound.rs
  src/blocks/speedtest.rs
  src/blocks/taskwarrior.rs
  src/blocks/temperature.rs
  src/blocks/toggle.rs
  src/blocks/uptime.rs
  src/blocks/watson.rs
  src/blocks/weather.rs
  src/blocks/xrandr.rs
Labels: cleanup

#947 Implement per-block colour overrides
  src/blocks.rs
  src/blocks/apt.rs
  src/blocks/backlight.rs
  src/blocks/battery.rs
  src/blocks/bluetooth.rs
  src/blocks/cpu.rs
  src/blocks/custom.rs
  src/blocks/custom_dbus.rs
  src/blocks/disk_space.rs
  src/blocks/docker.rs
  src/blocks/focused_window.rs
  src/blocks/github.rs
  src/blocks/hueshift.rs
  src/blocks/ibus.rs
  src/blocks/kdeconnect.rs
  src/blocks/keyboard_layout.rs
  src/blocks/load.rs
  src/blocks/maildir.rs
  src/blocks/memory.rs
  src/blocks/music.rs
  src/blocks/net.rs
  src/blocks/networkmanager.rs
  src/blocks/notify.rs
  src/blocks/notmuch.rs
  src/blocks/nvidia_gpu.rs
  src/blocks/pacman.rs
  src/blocks/pomodoro.rs
  src/blocks/sound.rs
  src/blocks/speedtest.rs
  src/blocks/taskwarrior.rs
  src/blocks/temperature.rs
  src/blocks/template.rs
  src/blocks/time.rs
  src/blocks/toggle.rs
  src/blocks/uptime.rs
  src/blocks/watson.rs
  src/blocks/weather.rs
  src/blocks/xrandr.rs
Labels: enhancement, fonts-and-rendering

#949 music block: implement format string
  src/blocks/music.rs
Labels: enhancement

#950 Fix clippy lints
  src/blocks/custom_dbus.rs
  src/blocks/music.rs
  src/blocks/speedtest.rs
Labels: cleanup

#953 Re-add `alternating_tint_fg`
  src/themes.rs
Labels: bug

#955 Fix clippy lints
  src/blocks/music.rs
Labels: cleanup
