Repository greshake/i3status-rust, pull requests merged in 2020-02, with the labels that each got.

#527 Document the optional `notmuch` block
  NEWS.md
  blocks.md
Labels: docs

#521 Convert to new Cargo.lock V2 format
  Cargo.lock
Labels: needs-rebase

#511 Chore: Order deps in alphabetical order
  Cargo.toml
Labels: needs-rebase

#556 Adds a man page
  .travis.yml
  man/_postface.1
  man/_preface.1
  man/generate.sh
  man/i3status-rs.1
Labels: docs, enhancement

#570 feat(net): support ppp vpn
  src/blocks/net.rs
Labels: enhancement
