Repository greshake/i3status-rust, pull requests merged in 2020-12, with the labels that each got.

#958 docs: mention places where escaping Pango chars may be required
  blocks.md
Labels: docs, fonts-and-rendering

#960 Update manpage
  man/i3status-rs.1
Labels: docs

#961 Update manpage
  man/_preface.1
  man/generate.sh
Labels: docs

#964 regen man
  man/i3status-rs.1
Labels: docs

#968 Bugfix for issue 965
  src/config.rs
  src/themes.rs
  src/util.rs
Labels: bug

#967 music block: handle case when metadata is unavailable
  src/blocks/music.rs
Labels: bug

#946 Document availability in home-manager
  README.md
Labels: docs

#972 music block bug fixes
  blocks.md
  src/blocks/music.rs
Labels: bug

#982 pacman: add option to hide when block up to date
  blocks.md
  src/blocks/pacman.rs
Labels: enhancement

#990 xrandr: do not leave zombies around
  src/blocks/xrandr.rs
Labels: bug

#993 net block: fix overflow panic
  src/blocks/net.rs
Labels: bug

#984 Add universal formatter
  blocks.md
  src/blocks/net.rs
  src/blocks/speedtest.rs
  src/util.rs
Labels: enhancement

#994 net block: always auto-discover devices if not explicitly set in config
  src/blocks/net.rs
Labels: bug

#995 Decode escaped unicode in SSID
  src/blocks/net.rs
Labels: enhancement
