Repository greshake/i3status-rust, pull requests merged in 2020-05, with the labels that each got.

#605 Use /sys/class/net/<device>/carrier instead of operstate in is_up()
  src/blocks/net.rs
Labels: discussion

#625 net block: add fallback to `wpa_cli` for retrieving SSID
  src/blocks/net.rs
Labels: awaiting confirmation of fix

#619 Update font awesome icons to version 5
  src/blocks/sound.rs
  src/icons.rs
Labels: fonts-and-rendering

#532 Add option to show marks instead of title
  src/blocks/focused_window.rs
Labels: needs-rebase, upstream bug

#684 Fix #89 support running a block only once
  blocks.md
  src/blocks.rs
  src/blocks/backlight.rs
  src/blocks/battery.rs
  src/blocks/bluetooth.rs
  src/blocks/cpu.rs
  src/blocks/custom.rs
  src/blocks/custom_dbus.rs
  src/blocks/disk_space.rs
  src/blocks/docker.rs
  src/blocks/focused_window.rs
  src/blocks/ibus.rs
  src/blocks/keyboard_layout.rs
  src/blocks/load.rs
  src/blocks/maildir.rs
  src/blocks/memory.rs
  src/blocks/music.rs
  src/blocks/net.rs
  src/blocks/networkmanager.rs
  src/blocks/notmuch.rs
  src/blocks/nvidia_gpu.rs
  src/blocks/pacman.rs
  src/blocks/pomodoro.rs
  src/blocks/sound.rs
  src/blocks/speedtest.rs
  src/blocks/taskwarrior.rs
  src/blocks/temperature.rs
  src/blocks/template.rs
  src/blocks/time.rs
  src/blocks/toggle.rs
  src/blocks/uptime.rs
  src/blocks/watson.rs
  src/blocks/weather.rs
  src/blocks/xrandr.rs
  src/de.rs
  src/scheduler.rs
Labels: enhancement

#690 weather block: add autolocate option
  blocks.md
  src/blocks/weather.rs
Labels: enhancement

#665 battery: read remaining time from time_to_empty_now and time_to_full_now if they exist
  src/blocks/battery.rs
Labels: enhancement

#425 Add GitHub block
  blocks.md
  src/blocks.rs
  src/blocks/github.rs
  src/icons.rs
  src/util.rs
Labels: enhancement

#704 net block: improve throughput formatting
  src/blocks/net.rs
Labels: enhancement

#707 speedtest block: improve throughput formatting
  src/blocks/net.rs
  src/blocks/speedtest.rs
  src/util.rs
Labels: enhancement

#701 Prevent bar being stopped by using signal other than SIGSTOP
  src/main.rs
Labels: enhancement
