Repository greshake/i3status-rust, pull requests merged in 2021-05, with the labels that each got.

#1212 custom_dbus: Unset icon if empty.
  src/blocks/custom_dbus.rs
Labels: bug/bugfix

#1217 chore: bump deps
  Cargo.lock
  Cargo.toml
  src/blocks/battery.rs
  src/blocks/custom_dbus.rs
  src/blocks/networkmanager.rs
Labels: rustc/dependency versions

#1213 Escape html entities in focused_window block
  src/blocks/focused_window.rs
Labels: bug/bugfix

#1218 chore: update man
  man/_preface.1
  man/i3status-rs.1
Labels: docs

#1220 fixed pacman printing to stdout/err
  src/blocks/pacman.rs
Labels: bug/bugfix

#1226 Adds example for custom pi-hole status block
  examples/README.md
Labels: docs

#1224 Fix json output of configuration error
  src/errors.rs
Labels: bug/bugfix

#1207 Add short_text support
  doc/blocks.md
  src/blocks/apt.rs
  src/blocks/battery.rs
  src/blocks/bluetooth.rs
  src/blocks/cpu.rs
  src/blocks/disk_space.rs
  src/blocks/docker.rs
  src/blocks/github.rs
  src/blocks/ibus.rs
  src/blocks/kdeconnect.rs
  src/blocks/keyboard_layout.rs
  src/blocks/load.rs
  src/blocks/memory.rs
  src/blocks/music.rs
  src/blocks/net.rs
  src/blocks/networkmanager.rs
  src/blocks/notify.rs
  src/blocks/pacman.rs
  src/blocks/sound.rs
  src/blocks/speedtest.rs
  src/blocks/taskwarrior.rs
  src/blocks/temperature.rs
  src/blocks/time.rs
  src/blocks/weather.rs
  src/blocks/xrandr.rs
  src/errors.rs
  src/formatting.rs
  src/main.rs
  src/widgets.rs
  src/widgets/text.rs
Labels: enhancement

#1229 Custom block example: liquid cooling system status
  examples/README.md
Labels: docs

#1227 memory: Count ZFS arc cache to cache to exclude from used memory
  src/blocks/memory.rs
Labels: enhancement

#1152 Cpu boost stat
  doc/blocks.md
  files/icons/awesome.toml
  files/icons/awesome5.toml
  files/icons/material-nf.toml
  files/icons/material.toml
  src/blocks/cpu.rs
  src/icons.rs
Labels: enhancement

#1240 pacman: fix default template not being used for `PacmanConfig::watched()`
  src/blocks/pacman.rs
Labels: bug/bugfix

#1241 pacman: fix invocation of fakeroot/pacman command
  src/blocks/pacman.rs
Labels: bug/bugfix

#1245 format strings: fix parsing of "unit" part
  src/formatting/placeholder.rs
Labels: bug/bugfix

#1233 Better error message on custom blocks
  src/blocks/custom.rs
Labels: bug/bugfix

#1250 Update themes.md
  doc/themes.md
Labels: docs

#1249 Add net support for material-icons
  files/icons/material.toml
Labels: themes/icons

#1248 formatting: refactor, implement prefix hiding and spacing
  src/formatting.rs
  src/formatting/placeholder.rs
  src/formatting/prefix.rs
  src/formatting/unit.rs
  src/formatting/value.rs
Labels: cleanup, configuration
