Repository greshake/i3status-rust, pull requests merged in 2021-12, with the labels that each got.

#1361 Add missing bat_not_available icon
  files/icons/material-nf.toml
Labels: bug/bugfix, themes/icons

#1358 Focused window format
  doc/blocks.md
  src/blocks/focused_window.rs
  src/blocks/net.rs
  src/util.rs
  src/widgets/rotatingtext.rs
Labels: enhancement

#1363 Revert "sound: detect more portable speaker types"
  src/blocks/sound.rs
Labels: bug/bugfix

#1356 Create rofication block
  doc/blocks.md
  src/blocks.rs
  src/blocks/rofication.rs
Labels: enhancement
