Repository greshake/i3status-rust, pull requests merged in 2021-02, with the labels that each got.

#1011 Refactored weather block to use curl crate
  Cargo.lock
  Cargo.toml
  blocks.md
  src/blocks/docker.rs
  src/blocks/github.rs
  src/blocks/weather.rs
  src/http.rs
  src/main.rs
Labels: enhancement

#1018 refactoring: fix all clippy warnings
  .gitignore
  src/blocks/github.rs
  src/blocks/hueshift.rs
  src/blocks/maildir.rs
  src/blocks/music.rs
  src/blocks/speedtest.rs
  src/blocks/weather.rs
  src/blocks/xrandr.rs
  src/util.rs
  src/widgets/rotatingtext.rs
Labels: cleanup

#1008 Support multiple filters in Taskwarrior block
  blocks.md
  src/blocks/taskwarrior.rs
Labels: enhancement

#1022 Update time-block docs to link to current chrono version
  blocks.md
Labels: docs

#1028 keyboard_layout: split layout name and variant in sway driver
  blocks.md
  src/blocks/keyboard_layout.rs
Labels: enhancement

#1031 cpu: fix "{frequency}" format in per-core mode
  blocks.md
  src/blocks/cpu.rs
  src/blocks/keyboard_layout.rs
Labels: bug

#975 kdeconnect: update for new D-Bus structure
  src/blocks/kdeconnect.rs
Labels: bug

#1027 Hueshift: add support for gammastep
  blocks.md
  src/blocks/hueshift.rs
Labels: enhancement

#1033 Change IDs to be `usize` instead of `String`
  Cargo.lock
  Cargo.toml
  src/blocks.rs
  src/blocks/apt.rs
  src/blocks/backlight.rs
  src/blocks/base_block.rs
  src/blocks/battery.rs
  src/blocks/bluetooth.rs
  src/blocks/cpu.rs
  src/blocks/custom.rs
  src/blocks/custom_dbus.rs
  src/blocks/disk_space.rs
  src/blocks/docker.rs
  src/blocks/focused_window.rs
  src/blocks/github.rs
  src/blocks/hueshift.rs
  src/blocks/ibus.rs
  src/blocks/kdeconnect.rs
  src/blocks/keyboard_layout.rs
  src/blocks/load.rs
  src/blocks/maildir.rs
  src/blocks/memory.rs
  src/blocks/music.rs
  src/blocks/net.rs
  src/blocks/networkmanager.rs
  src/blocks/notify.rs
  src/blocks/notmuch.rs
  src/blocks/nvidia_gpu.rs
  src/blocks/pacman.rs
  src/blocks/pomodoro.rs
  src/blocks/sound.rs
  src/blocks/speedtest.rs
  src/blocks/taskwarrior.rs
  src/blocks/temperature.rs
  src/blocks/template.rs
  src/blocks/time.rs
  src/blocks/toggle.rs
  src/blocks/uptime.rs
  src/blocks/watson.rs
  src/blocks/weather.rs
  src/blocks/xrandr.rs
  src/input.rs
  src/main.rs
  src/scheduler.rs
  src/util.rs
  src/widgets/button.rs
  src/widgets/graph.rs
  src/widgets/rotatingtext.rs
  src/widgets/text.rs
Labels: cleanup

#1041 memory: fix `clickable`
  src/blocks/memory.rs
Labels: bug

#1039 remove redundant ConfigLegacy structure
  src/config.rs
  src/main.rs
  src/themes.rs
  src/util.rs
Labels: cleanup

#1044 update man
  man/i3status-rs.1
Labels: docs

#1055 fix loading theme form file
  src/themes.rs
Labels: bug

#1042 Do not copy the entire config to every widget
  blocks.md
  src/blocks.rs
  src/blocks/apt.rs
  src/blocks/backlight.rs
  src/blocks/base_block.rs
  src/blocks/battery.rs
  src/blocks/bluetooth.rs
  src/blocks/cpu.rs
  src/blocks/custom.rs
  src/blocks/custom_dbus.rs
  src/blocks/disk_space.rs
  src/blocks/docker.rs
  src/blocks/focused_window.rs
  src/blocks/github.rs
  src/blocks/hueshift.rs
  src/blocks/ibus.rs
  src/blocks/kdeconnect.rs
  src/blocks/keyboard_layout.rs
  src/blocks/load.rs
  src/blocks/maildir.rs
  src/blocks/memory.rs
  src/blocks/music.rs
  src/blocks/net.rs
  src/blocks/networkmanager.rs
  src/blocks/notify.rs
  src/blocks/notmuch.rs
  src/blocks/nvidia_gpu.rs
  src/blocks/pacman.rs
  src/blocks/pomodoro.rs
  src/blocks/sound.rs
  src/blocks/speedtest.rs
  src/blocks/taskwarrior.rs
  src/blocks/temperature.rs
  src/blocks/template.rs
  src/blocks/time.rs
  src/blocks/toggle.rs
  src/blocks/uptime.rs
  src/blocks/watson.rs
  src/blocks/weather.rs
  src/blocks/xrandr.rs
  src/config.rs
  src/main.rs
  src/util.rs
  src/widget.rs
  src/widgets.rs
  src/widgets/button.rs
  src/widgets/graph.rs
  src/widgets/rotatingtext.rs
  src/widgets/text.rs
Labels: cleanup

#1009 Add documentation for color_overrides
  themes.md
Labels: docs

#1063 net: add `clickable` option and `format_alt` formating option
  blocks.md
  src/blocks/net.rs
Labels: configuration, enhancement

#1059 keyboard_layout: add {layout_short} format option
  blocks.md
  src/blocks/keyboard_layout.rs
Labels: enhancement

#1067 Copy some docs from the wiki to the code
  src/blocks.rs
Labels: docs

#1070 Add fallback for older systems that don't have `sensors -j`
  blocks.md
  src/blocks/temperature.rs
Labels: enhancement

#1071 sound block: fix spacing for empty format strings
  src/blocks/sound.rs
Labels: fonts-and-rendering

#1072 net block: fix spacing for empty format strings
  src/blocks/net.rs
Labels: fonts-and-rendering

#1073 net: remove deprecated options and redundant widget
  blocks.md
  src/blocks/net.rs
Labels: cleanup

#1082 Improve #1079
  src/blocks/net.rs
Labels: cleanup

#1080 Remove graph widget
  src/widgets.rs
  src/widgets/graph.rs
Labels: cleanup

#1076 Simplify `FormatTemplate`
  src/blocks/weather.rs
  src/util.rs
Labels: cleanup

#1085 Introduce I3BlockData structure, do not call `click()` on every block
  src/blocks.rs
  src/blocks/apt.rs
  src/blocks/backlight.rs
  src/blocks/base_block.rs
  src/blocks/battery.rs
  src/blocks/bluetooth.rs
  src/blocks/cpu.rs
  src/blocks/custom.rs
  src/blocks/custom_dbus.rs
  src/blocks/disk_space.rs
  src/blocks/docker.rs
  src/blocks/focused_window.rs
  src/blocks/github.rs
  src/blocks/hueshift.rs
  src/blocks/ibus.rs
  src/blocks/kdeconnect.rs
  src/blocks/keyboard_layout.rs
  src/blocks/load.rs
  src/blocks/maildir.rs
  src/blocks/memory.rs
  src/blocks/music.rs
  src/blocks/net.rs
  src/blocks/networkmanager.rs
  src/blocks/notify.rs
  src/blocks/notmuch.rs
  src/blocks/nvidia_gpu.rs
  src/blocks/pacman.rs
  src/blocks/pomodoro.rs
  src/blocks/sound.rs
  src/blocks/speedtest.rs
  src/blocks/taskwarrior.rs
  src/blocks/temperature.rs
  src/blocks/template.rs
  src/blocks/time.rs
  src/blocks/toggle.rs
  src/blocks/uptime.rs
  src/blocks/watson.rs
  src/blocks/weather.rs
  src/blocks/xrandr.rs
  src/input.rs
  src/main.rs
  src/util.rs
  src/widgets.rs
  src/widgets/i3block_data.rs
  src/widgets/rotatingtext.rs
  src/widgets/text.rs
Labels: cleanup

#1087 I3BlockData: allow `min_width` in pixels; fix `align` rendering
  src/widgets/i3block_data.rs
  src/widgets/rotatingtext.rs
Labels: bug, fonts/spacing/rendering

#1090 Remove trailing comma
  src/widgets/i3block_data.rs
Labels: bug

#1083 introduce `debug_borders` feature
  Cargo.toml
  src/widgets/i3block_data.rs
  src/widgets/rotatingtext.rs
  src/widgets/text.rs
Labels: enhancement, fonts/spacing/rendering

#1099 networkmanager: Avoid duplicate device with VPN connections.
  src/blocks/networkmanager.rs
Labels: awaiting confirmation of fix, enhancement

#1102 Fixed wpa_cli BSSID being displayed instead of SSID, see #1100
  src/blocks/net.rs
Labels: bug

#1095 add "material-nf" icon set, add `icons_format` config option
  README.md
  src/blocks.rs
  src/blocks/backlight.rs
  src/blocks/base_block.rs
  src/config.rs
  src/icons.rs
  themes.md
Labels: enhancement, fonts/spacing/rendering, themes/icons
