Repository greshake/i3status-rust, pull requests merged in 2021-08, with the labels that each got.

#1286 Github, Nvidia_gpu, Temperature block additions and changes
  doc/blocks.md
  src/blocks/github.rs
  src/blocks/nvidia_gpu.rs
  src/blocks/temperature.rs
  src/errors.rs
  src/main.rs
Labels: enhancement

#1282 add more battery icons
  files/icons/awesome.toml
  files/icons/awesome5.toml
  files/icons/material-nf.toml
  files/icons/material.toml
  src/blocks/battery.rs
  src/blocks/kdeconnect.rs
  src/util.rs
Labels: fonts/spacing/rendering

#1289 http: Replace spaces in URL with "%20"
  src/http.rs
Labels: bug/bugfix

#1296 Fix nvidia block falling behind on lines from nvidia-smi
  src/blocks/nvidia_gpu.rs
Labels: bug/bugfix

#1298 Add mising quote in pomodoro block example
  doc/blocks.md
Labels: docs
