Repository greshake/i3status-rust, pull requests merged in 2021-11, with the labels that each got.

#1327 Fix music marquee updates after closing player
  src/main.rs
  src/scheduler.rs
Labels: bug/bugfix

#1325 [custom block] Add watch files feature with inotify
  Cargo.lock
  Cargo.toml
  doc/blocks.md
  src/blocks/custom.rs
Labels: enhancement

#1331 music block: pango escape default text icons
  src/icons.rs
Labels: bug/bugfix

#1329 custom_dbus: add option to clear contents after timeout expires
  src/blocks/custom_dbus.rs
Labels: enhancement

#1330 custom_dbus: allow initial text to be customised
  src/blocks/custom_dbus.rs
Labels: enhancement

#1337 hueshift block: Add support for wlsunset
  src/blocks/hueshift.rs
Labels: enhancement

#1342 ibus block: tolerate errors better
  src/blocks/ibus.rs
Labels: bug/bugfix

#1344 Update man
  man/generate.sh
  man/i3status-rs.1
Labels: docs

#1352 Add Nextcloud example to examples doc
  examples/README.md
Labels: docs

#1348 sound: detect more portable speaker types
  src/blocks/sound.rs
Labels: enhancement

#1349 `backlight` block: adapt configuration options to precedent set by `sound` block
  doc/blocks.md
  src/blocks/backlight.rs
Labels: enhancement

#1355 docker: expand socket path
  src/blocks/docker.rs
Labels: enhancement
