Repository greshake/i3status-rust, pull requests merged in 2021-04, with the labels that each got.

#1151 Do not apply engineering notation to values without units
  src/formatting/value.rs
Labels: bug/bugfix

#1157 Allow custom blocks with JSON not to set an icon
  src/blocks/custom.rs
  src/widgets/text.rs
Labels: bug/bugfix

#1159 regenerate man
  man/generate.sh
  man/i3status-rs.1
Labels: docs

#1158 [icons] Use 8-nibble codepoints instead of (invalid) 5-nibble ones
  files/icons/awesome.toml
  files/icons/awesome5.toml
Labels: bug/bugfix

#1162 Fix a typo
  src/blocks/net.rs
  src/formatting/placeholder.rs
Labels: bug/bugfix

#1165 README.md: Update blocks documentation link
  README.md
Labels: docs

#1167 Fix some icons (related with #1163)
  files/icons/awesome.toml
  files/icons/awesome5.toml
  files/icons/material.toml
Labels: bug/bugfix

#1154 Include "Power Draw" option for Nvidia GPU block
  doc/blocks.md
  src/blocks/nvidia_gpu.rs
Labels: enhancement

#1172 Fix typos
  doc/blocks.md
Labels: docs

#1174 Introduce `FormatTemplate::contains()`; fix net block
  src/blocks/net.rs
  src/formatting.rs
Labels: bug/bugfix

#1177 Replace FontAwesome5 disk_drive icon to be free
  files/icons/awesome5.toml
Labels: themes/icons

#1176 Add disk_drive icon override to docs
  doc/themes.md
Labels: docs, themes/icons

#1175 Nord dark theme
  doc/themes.md
  files/themes/nord-dark.toml
  img/themes/nord-dark.png
Labels: themes/icons

#1179 music block: escape pango
  src/widgets/rotatingtext.rs
Labels: bug/bugfix

#1178 Net block: do not throw an error if frequency/signal is unavailable
  src/blocks/net.rs
Labels: bug/bugfix

#1180 fix: typo
  doc/themes.md
Labels: docs

#1169 weather: support config language
  doc/blocks.md
  src/blocks/weather.rs
Labels: enhancement

#1187 disk_space: fix alert_absolute
  src/blocks/disk_space.rs
Labels: bug/bugfix

#1194 Add apt on_click example
  doc/blocks.md
Labels: docs

#1195 Remove quotes from weather block
  src/blocks/weather.rs
Labels: bug/bugfix
