Repository greshake/i3status-rust, pull requests merged in 2021-03, with the labels that each got.

#1106 Refactor icons deserialization and add ability to load icons from file
  src/config.rs
  src/de.rs
  src/icons.rs
  src/themes.rs
  src/util.rs
  themes.md
Labels: cleanup, enhancement

#1110 kdeconnect: change version check mechanism
  src/blocks/kdeconnect.rs
Labels: bug/bugfix

#1112 Implement new formatting mechanism
  NEWS.md
  README.md
  blocks.md
  src/blocks/apt.rs
  src/blocks/backlight.rs
  src/blocks/battery.rs
  src/blocks/bluetooth.rs
  src/blocks/cpu.rs
  src/blocks/custom.rs
  src/blocks/custom_dbus.rs
  src/blocks/disk_space.rs
  src/blocks/docker.rs
  src/blocks/github.rs
  src/blocks/ibus.rs
  src/blocks/kdeconnect.rs
  src/blocks/keyboard_layout.rs
  src/blocks/load.rs
  src/blocks/maildir.rs
  src/blocks/memory.rs
  src/blocks/music.rs
  src/blocks/net.rs
  src/blocks/networkmanager.rs
  src/blocks/notify.rs
  src/blocks/notmuch.rs
  src/blocks/nvidia_gpu.rs
  src/blocks/pacman.rs
  src/blocks/pomodoro.rs
  src/blocks/sound.rs
  src/blocks/speedtest.rs
  src/blocks/taskwarrior.rs
  src/blocks/temperature.rs
  src/blocks/time.rs
  src/blocks/toggle.rs
  src/blocks/uptime.rs
  src/blocks/weather.rs
  src/blocks/xrandr.rs
  src/config.rs
  src/errors.rs
  src/formatting.rs
  src/formatting/placeholder.rs
  src/formatting/prefix.rs
  src/formatting/unit.rs
  src/formatting/value.rs
  src/main.rs
  src/signals.rs
  src/util.rs
  src/widgets/rotatingtext.rs
  src/widgets/text.rs
Labels: enhancement

#1126 `impl Default` for blocks' configs
  src/blocks/apt.rs
  src/blocks/backlight.rs
  src/blocks/battery.rs
  src/blocks/cpu.rs
  src/blocks/custom.rs
  src/blocks/custom_dbus.rs
  src/blocks/disk_space.rs
  src/blocks/docker.rs
  src/blocks/focused_window.rs
  src/blocks/github.rs
  src/blocks/hueshift.rs
  src/blocks/ibus.rs
  src/blocks/kdeconnect.rs
  src/blocks/keyboard_layout.rs
  src/blocks/load.rs
  src/blocks/maildir.rs
  src/blocks/memory.rs
  src/blocks/music.rs
  src/blocks/net.rs
  src/blocks/networkmanager.rs
  src/blocks/notify.rs
  src/blocks/notmuch.rs
  src/blocks/nvidia_gpu.rs
  src/blocks/pacman.rs
  src/blocks/pomodoro.rs
  src/blocks/sound.rs
  src/blocks/speedtest.rs
  src/blocks/temperature.rs
  src/blocks/template.rs
  src/blocks/time.rs
  src/blocks/uptime.rs
  src/blocks/watson.rs
  src/blocks/xrandr.rs
Labels: cleanup

#1128 music block: merge two threads into one
  src/blocks/music.rs
Labels: cleanup

#1129 group protocol-related code together
  src/blocks.rs
  src/blocks/apt.rs
  src/blocks/backlight.rs
  src/blocks/base_block.rs
  src/blocks/bluetooth.rs
  src/blocks/custom.rs
  src/blocks/hueshift.rs
  src/blocks/ibus.rs
  src/blocks/memory.rs
  src/blocks/music.rs
  src/blocks/net.rs
  src/blocks/notify.rs
  src/blocks/notmuch.rs
  src/blocks/nvidia_gpu.rs
  src/blocks/pacman.rs
  src/blocks/pomodoro.rs
  src/blocks/sound.rs
  src/blocks/speedtest.rs
  src/blocks/taskwarrior.rs
  src/blocks/temperature.rs
  src/blocks/template.rs
  src/blocks/toggle.rs
  src/blocks/watson.rs
  src/blocks/weather.rs
  src/blocks/xrandr.rs
  src/config.rs
  src/main.rs
  src/protocol/i3bar_block.rs
  src/protocol/i3bar_event.rs
  src/protocol/mod.rs
  src/util.rs
  src/widgets.rs
  src/widgets/rotatingtext.rs
  src/widgets/text.rs
Labels: cleanup

#1131 Implement config reloading
  src/main.rs
Labels: enhancement

#1141 Udate example config with new placeholder format
  example_config.toml
Labels: configuration, docs

#1140 Allow reloading with usr2 signal after displaying error
  src/main.rs
Labels: enhancement
