Repository greshake/i3status-rust, pull requests merged in 2021-07, with the labels that each got.

#1281 fix `temperature` block fallback
  src/blocks/temperature.rs
Labels: bug/bugfix

#1284 themes/slick: do not modify transparency via alternating tints
  files/themes/slick.toml
Labels: themes/icons

#1279 Add possibility to unset colors using overrides
  src/config.rs
  src/errors.rs
  src/protocol/i3bar_block.rs
  src/protocol/mod.rs
  src/themes.rs
  src/util.rs
  src/widgets.rs
Labels: enhancement
