Repository greshake/i3status-rust, pull requests merged in 2022-07, with the labels that each got.

#1412 Add srcery color theme
  doc/themes.md
  files/themes/srcery.toml
  img/themes/srcery.png
Labels: themes/icons

#1573 Use API data for AT instead of calculating
  src/blocks/weather.rs
Labels: cleanup

#1563 pacman: don't use sh to run fakeroot
  src/blocks/pacman.rs
Labels: cleanup

#1577 weather: Add support for met.no
  src/blocks/weather.rs
  src/blocks/weather/met_no.rs
  src/blocks/weather/open_weather_map.rs
Labels: enhancement
