Repository greshake/i3status-rust, pull requests merged in 2022-09, with the labels that each got.

#1621 formatting: embed icons using ^icon syntax
  src/blocks.rs
  src/blocks/net.rs
  src/blocks/speedtest.rs
  src/config.rs
  src/formatting.rs
  src/formatting/formatter.rs
  src/formatting/template.rs
  src/formatting/value.rs
  src/widget.rs
Labels: enhancement, discussion, themes/icons

#1625 backlight: add a workaround for ddcci
  src/blocks/backlight.rs
Labels: bug/bugfix

#1618 Drop hard-coded whitespace and render icon as a placeholder
  NEWS.md
  examples/config.toml
  src/blocks.rs
  src/blocks/apt.rs
  src/blocks/backlight.rs
  src/blocks/battery.rs
  src/blocks/bluetooth.rs
  src/blocks/cpu.rs
  src/blocks/custom.rs
  src/blocks/custom_dbus.rs
  src/blocks/disk_space.rs
  src/blocks/dnf.rs
  src/blocks/docker.rs
  src/blocks/external_ip.rs
  src/blocks/focused_window.rs
  src/blocks/github.rs
  src/blocks/hueshift.rs
  src/blocks/kdeconnect.rs
  src/blocks/keyboard_layout.rs
  src/blocks/load.rs
  src/blocks/maildir.rs
  src/blocks/memory.rs
  src/blocks/music.rs
  src/blocks/net.rs
  src/blocks/notify.rs
  src/blocks/notmuch.rs
  src/blocks/nvidia_gpu.rs
  src/blocks/pacman.rs
  src/blocks/pomodoro.rs
  src/blocks/rofication.rs
  src/blocks/sound.rs
  src/blocks/speedtest.rs
  src/blocks/taskwarrior.rs
  src/blocks/temperature.rs
  src/blocks/time.rs
  src/blocks/toggle.rs
  src/blocks/uptime.rs
  src/blocks/watson.rs
  src/blocks/weather.rs
  src/blocks/xrandr.rs
  src/config.rs
  src/formatting.rs
  src/formatting/config.rs
  src/widget.rs
Labels: enhancement, fonts/spacing/rendering
