Repository greshake/i3status-rust, pull requests merged in 2022-04, with the labels that each got.

#1453 Shellexpand on blocks
  doc/blocks.md
  src/blocks/disk_space.rs
  src/blocks/maildir.rs
  src/blocks/notmuch.rs
  src/blocks/rofication.rs
  src/blocks/watson.rs
Labels: enhancement, configuration

#1461 battery: remove allow_missing
  doc/blocks.md
  src/blocks/battery.rs
Labels: cleanup, breaking

#1457 Net graph formatting
  doc/blocks.md
  src/blocks/net.rs
  src/formatting.rs
  src/formatting/placeholder.rs
  src/formatting/prefix.rs
  src/formatting/value.rs
  src/util.rs
Labels: enhancement
