Repository greshake/i3status-rust, pull requests merged in 2022-02, with the labels that each got.

#1417 Issue 1405
  src/blocks/battery.rs
Labels: bug/bugfix

#1423 Fix a typo in blocks.md
  doc/blocks.md
Labels: docs

#1415 add if_command field to block config
  examples/config.toml
  src/blocks.rs
  src/blocks/base_block.rs
  src/main.rs
Labels: enhancement

#1429 Adjust example; BAT0 is typically a symlink
  examples/config.toml
Labels: docs

#1438 sound: check DEVICE_FORM_FACTOR property
  src/blocks/sound.rs
Labels: enhancement
