Repository greshake/i3status-rust, pull requests merged in 2022-01, with the labels that each got.

#1382 Fix version info collect at build time
  build.rs
Labels: bug/bugfix

#1380 Added hint on Maildir block documentation
  doc/blocks.md
Labels: docs

#1391 Rofication: Remove extra allocation
  src/blocks/rofication.rs
Labels: cleanup

#1383 Add new apcupsd battery driver
  doc/blocks.md
  src/apcaccess.rs
  src/blocks/battery.rs
  src/main.rs
Labels: enhancement

#1386 Add support for the xkb-switch keyboard layout reader.
  doc/blocks.md
  src/blocks/keyboard_layout.rs
Labels: enhancement

#1378 Enable allow_missing for the UPower driver
  doc/blocks.md
  src/blocks/battery.rs
Labels: enhancement

#1394 Named PA sound devices don't know current volume
  src/blocks/sound.rs
Labels: bug/bugfix

#1393 Fix for batteries allow_missing
  src/apcaccess.rs
  src/blocks/battery.rs
Labels: bug/bugfix

#1398 hueshift: Replace killall with pkill
  src/blocks/hueshift.rs
Labels: bug/bugfix

#1409 Issue-1405: UPower property type mismatch
  src/blocks/battery.rs
Labels: bug/bugfix

#1375 temperature: use libsensors bindings instead of sensors binary
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  doc/blocks.md
  doc/dev.md
  src/blocks/temperature.rs
Labels: cleanup

#1411 hueshift: do not leave zombies
  src/blocks/hueshift.rs
Labels: bug/bugfix
