Repository greshake/i3status-rust, pull requests merged in 2023-03, with the labels that each got.

#1827 fix: hueshift block step now maxes at 500
  src/blocks/hueshift.rs
Labels: bug/bugfix

#1725 Feature: VPN block
  src/blocks.rs
  src/blocks/vpn.rs
Labels: enhancement

#1847 manual_install.md: optional notmuch block depends upon libnotmuch.so
  doc/manual_install.md
Labels: docs
