Repository greshake/i3status-rust, pull requests merged in 2023-02, with the labels that each got.

#1698 formatting: implement named arguments instead of positional
  Cargo.lock
  Cargo.toml
  src/blocks/apt.rs
  src/blocks/custom.rs
  src/blocks/custom_dbus.rs
  src/blocks/dnf.rs
  src/blocks/docker.rs
  src/blocks/focused_window.rs
  src/blocks/github.rs
  src/blocks/load.rs
  src/blocks/memory.rs
  src/blocks/music.rs
  src/blocks/net.rs
  src/blocks/pacman.rs
  src/blocks/rofication.rs
  src/blocks/sound.rs
  src/blocks/taskwarrior.rs
  src/config.rs
  src/escape.rs
  src/formatting.rs
  src/formatting/config.rs
  src/formatting/formatter.rs
  src/formatting/parse.rs
  src/formatting/template.rs
  src/main.rs
Labels: discussion, breaking

#1713 replace cpu icon with cpu_{low,med,high}
  files/icons/awesome.toml
  files/icons/awesome5.toml
  files/icons/awesome6.toml
  files/icons/material-nf.toml
  files/icons/material.toml
  src/blocks/cpu.rs
Labels: themes/icons, breaking

#1710 Add playerctld support to music block
  src/blocks/music.rs
  src/blocks/music/zbus_playerctld.rs
Labels: enhancement

#1718 music: remove seek_step, add seek_step_secs
  src/blocks/music.rs
  src/wrappers.rs
Labels: breaking

#1723 Add datetime value parser
  src/blocks/time.rs
  src/formatting.rs
  src/formatting/config.rs
  src/formatting/formatter.rs
  src/formatting/parse.rs
  src/formatting/value.rs
Labels: enhancement, breaking

#1720 allow icon configs to contain lists instead of strings, remove icons such as bat_N
  files/icons/awesome.toml
  files/icons/awesome5.toml
  files/icons/awesome6.toml
  files/icons/material-nf.toml
  files/icons/material.toml
  src/blocks.rs
  src/blocks/backlight.rs
  src/blocks/battery.rs
  src/blocks/cpu.rs
  src/blocks/kdeconnect.rs
  src/blocks/sound.rs
  src/config.rs
  src/formatting/template.rs
  src/icons.rs
  src/util.rs
Labels: configuration, themes/icons, breaking

#1730 Fix tea icon for awesome4
  files/icons/awesome4.toml
Labels: bug/bugfix, themes/icons

#1722 MPRIS music volume
  src/blocks/music.rs
  src/blocks/sound.rs
Labels: enhancement

#1735 Rofication block: Add required LF to num
  src/blocks/rofication.rs
Labels: bug/bugfix

#1737 Add width, w for constant width on formatter
  src/formatting.rs
  src/formatting/formatter.rs
Labels: enhancement

#1748 Fix time block locale
  src/formatting/formatter.rs
Labels: bug/bugfix

#1749 music: make volume optional
  src/blocks/music.rs
Labels: bug/bugfix

#1765 Update NEWS.md
  NEWS.md
Labels: docs

#1779 Stop find_files requiring a specific extension
  src/util.rs
Labels: enhancement
