Repository greshake/i3status-rust, pull requests merged in 2023-09, with the labels that each got.

#1940 weather(metno): weathericon API was terminated, use pre-fetched data
  NEWS.md
  cspell.yaml
  src/blocks/weather/met_no.rs
  src/blocks/weather/met_no_legends.json
Labels: bug/bugfix

#1729 Add new emoji icon set 🙂
  doc/themes.md
  files/icons/emoji.toml
Labels: themes/icons

#1936 switch to std::sync::mpsc from crossbeam-channel
  Cargo.lock
  Cargo.toml
  src/blocks/sound/pulseaudio.rs
Labels: dependencies
